# Файл: netlify.toml (Финальная версия)

# --- Настройки сборки ---
[build]
  # Эта настройка гарантирует, что Netlify не будет пропускать сборки,
  # а всегда будет собирать самую последнюю версию вашего репозитория.
  [build.processing]
    skip_processing = false

# --- Настройки заголовков ---
[[headers]]
  # Это правило для YML-фидов (для Яндекса)
  for = "/*.yml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
