# Netlify конфигурация для ButlerSPB Blog

[build]
  publish = "dist"
  command = "NODE_OPTIONS='--max-old-space-size=4096' npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  
# Настройки деплоя
[context.production]
  command = "NODE_OPTIONS='--max-old-space-size=4096' npm run build"
  
[context.deploy-preview]
  command = "NODE_OPTIONS='--max-old-space-size=4096' npm run build"
  
[context.branch-deploy]
  command = "NODE_OPTIONS='--max-old-space-size=4096' npm run build"

# Редиректы для SEO
[[redirects]]
  from = "/blog/index"
  to = "/blog"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# Заголовки для безопасности и производительности
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ВАШЕ ПРАВИЛО ДЛЯ YML ФАЙЛОВ
[[headers]]
  for = "/*.yml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

# Сжатие контента
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Плагины для оптимизации
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  
  [plugins.inputs]
    baseUrl = "https://butlerspb-blog.netlify.app"
    sitemapPath = "/sitemap.xml"
    providers = [
      "google",
      "bing",
      "yandex"
    ]

# Функции (для будущего расширения)
[functions]
  directory = "functions"
  node_bundler = "esbuild"

# Переменные окружения (публичные)
[build.environment]
  ASTRO_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
