name: 🚀 Content Factory (Bulletproof)

on:
  workflow_dispatch:
    inputs:
      model_choice:
        description: 'Какую модель использовать для генерации?'
        required: true
        default: 'gemini'
        type: choice
        options:
        - gemini
        - deepseek
      batch_size_per_thread:
        description: 'Сколько статей генерировать КАЖДЫМ потоком?'
        required: true
        default: '10'
      threads:
        description: 'Сколько потоков запустить ОДНОВРЕМЕННО (1-20)?'
        required: true
        default: '5'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: Create thread matrix
        id: set_matrix
        run: |
          MAX_THREADS=20
          REQUESTED_THREADS=${{ github.event.inputs.threads || 5 }}
          
          if (( REQUESTED_THREADS > MAX_THREADS )); then
            echo "::warning::Запрошено больше потоков (${REQUESTED_THREADS}), чем доступно ключей (${MAX_THREADS}). Будет использовано ${MAX_THREADS}."
            REQUESTED_THREADS=$MAX_THREADS
          fi

          MATRIX=$(jq -cn --argjson n "$REQUESTED_THREADS" '[range(1; $n + 1)]')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  generate_and_publish:
    needs: prepare
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        thread: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - name: ⬇️ Checkout repo (Thread ${{ matrix.thread }})
        uses: actions/checkout@v4
        with:
          # Важно: используем токен для возможности пушить обратно
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⚙️ Setup Node.js (Thread ${{ matrix.thread }})
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install dependencies (Thread ${{ matrix.thread }})
        run: npm install

      - name: 🔑 Set API Key for Thread ${{ matrix.thread }}
        id: set_key
        run: |
          MODEL_CHOICE="${{ github.event.inputs.model_choice || 'gemini' }}"
          if [ "$MODEL_CHOICE" == "deepseek" ]; then
            API_KEYS="${{ secrets.OPENROUTER_API_KEYS_POOL }}"
          else
            API_KEYS="${{ secrets.GEMINI_API_KEYS_POOL }}"
          fi
          
          CURRENT_KEY=$(echo "$API_KEYS" | sed -n '${{ matrix.thread }}p' | tr -d '\r')

          if [[ -z "$CURRENT_KEY" ]]; then
            echo "::error::Не удалось извлечь API-ключ для потока #${{ matrix.thread }} для модели ${MODEL_CHOICE}."
            exit 1
          fi
          echo "key=$CURRENT_KEY" >> $GITHUB_OUTPUT

      - name: 🏭 Run Factory (Thread ${{ matrix.thread }})
        env:
          MODEL_CHOICE: ${{ github.event.inputs.model_choice || 'gemini' }}
          API_KEY_CURRENT: ${{ steps.set_key.outputs.key }}
          BATCH_SIZE: ${{ github.event.inputs.batch_size_per_thread || 10 }}
          TOTAL_THREADS: ${{ github.event.inputs.threads || 5 }}
          THREAD_ID: ${{ matrix.thread }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          
          echo "--- ЭСКАДРОН #${{ matrix.thread }}: Начинаю генерацию ---"
          
          npm run factory
          
          echo "✅ ЭСКАДРОН #${{ matrix.thread }}: Миссия успешно завершена."
