name: 🚀 Content Factory (Synchronized Strike)

on:
  workflow_dispatch:
    inputs:
      batch_size_per_thread:
        description: 'Сколько статей генерировать КАЖДЫМ потоком?'
        required: true
        default: '10'
      threads:
        description: 'Сколько потоков запустить ОДНОВРЕМЕННО (1-20)?'
        required: true
        default: '5'

jobs:
  # --- ЗАДАЧА №1: ПАРАЛЛЕЛЬНАЯ ГЕНЕРАЦИЯ И ПУБЛИКАЦИЯ ---
  generate_and_publish:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    
    outputs:
      # Мы будем собирать все новые URL со всех потоков здесь
      all_new_urls: ${{ steps.factory.outputs.urllist }}
      
    strategy:
      fail-fast: false
      matrix:
        thread: ${{ fromJson(format('[{0}]', range(1, github.event.inputs.threads + 1))) }}

    steps:
      - name: ⬇️ Checkout repo (Thread ${{ matrix.thread }})
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: ⚙️ Setup Node.js (Thread ${{ matrix.thread }})
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install dependencies (Thread ${{ matrix.thread }})
        run: npm install

      - name: 🔑 Set API Key for Thread ${{ matrix.thread }}
        id: set_key
        # ... (этот шаг не меняется)

      - name: 🏭 Run Factory & Publish (Thread ${{ matrix.thread }})
        id: factory # Даем этому шагу ID
        env:
          # ... (этот env блок не меняется)
        run: |
          # ... (весь код генерации и git push остается тем же)
          
          # --- ИЗМЕНЕНИЕ: Собираем URL для передачи на СЛЕДУЮЩУЮ ЗАДАЧУ ---
          URL_LIST=""
          # ... (логика с git diff и циклом for для сбора URL)
          
          echo "urllist<<EOF" >> $GITHUB_OUTPUT
          echo -e "$URL_LIST" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  # --- ЗАДАЧА №2: ОЖИДАНИЕ И ОТПРАВКА В INDEXNOW ---
  notify:
    # Эта задача ждет, пока ВСЕ задачи из 'generate_and_publish' завершатся
    needs: generate_and_publish
    # Выполняется всегда, если есть что отправлять
    if: always() && needs.generate_and_publish.outputs.all_new_urls

    runs-on: ubuntu-latest
    steps:
      - name: ⏸️ Tactical Pause for Netlify Build
        run: |
          echo "Делаю тактическую паузу на 90 секунд, чтобы дать Netlify время на сборку сайта..."
          sleep 90
          echo "Пауза завершена. Начинаю отправку в IndexNow."

      - name: 📢 Notify IndexNow (Yandex & Bing)
        run: |
          echo "Отправляю уведомление о новых страницах в IndexNow..."
          API_KEY="d1b055ab1eb146d892169bbb2c96550e"
          HOST="butlerspb-blog.netlify.app"
          
          # Получаем список URL из ВЫХОДНЫХ ДАННЫХ предыдущей задачи
          URL_LIST_STRING='${{ needs.generate_and_publish.outputs.all_new_urls }}'
          
          if [[ -z "$URL_LIST_STRING" ]]; then
            echo "✅ Новых URL для отправки не найдено."
            exit 0
          fi

          JSON_PAYLOAD=$(jq -n \
                          --arg host "$HOST" \
                          --arg key "$API_KEY" \
                          --arg urls_string "$URL_LIST_STRING" \
                          '{host: $host, key: $key, urlList: ($urls_string | split("\n") | map(select(length > 0)))}'
                          )
          
          echo "--- Финальный пакет для отправки ---"
          echo "$JSON_PAYLOAD"
          
          curl -X POST "https://yandex.com/indexnow" -H "Content-Type: application/json; charset=utf-8" -d "$JSON_PAYLOAD"
          curl -X POST "https://www.bing.com/indexnow" -H "Content-Type: application/json; charset=utf-8" -d "$JSON_PAYLOAD"
          echo -e "\nУведомления отправлены."
