name: 🚀 Content Factory (Surgical Precision)

on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'Сколько статей генерировать за 1 итерацию?'
        required: true
        default: '50'
      iterations:
        description: 'Сколько раз запустить конвейер?'
        required: true
        default: '10'

jobs:
  build:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏭 Run Content Factory Conveyor
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BATCH_SIZE: ${{ github.event.inputs.batch_size }}
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          
          for i in $(seq 1 ${{ github.event.inputs.iterations }})
          do
            echo "--- КОНВЕЙЕР: Запуск итерации $i из ${{ github.event.inputs.iterations }} ---"
            
            commit_before=$(git rev-parse HEAD)
            
            npm run factory
            
            if [[ -z $(git status --porcelain) ]]; then
              echo "✅ Новых статей в этой итерации нет. Работа полностью завершена."
              break
            fi

            echo "🔥 Обнаружены новые файлы. Добавляю в индекс и выполняю коммит..."
            git add .
            git commit -m "🚀 Авто-публикация: пачка статей №$i"

            echo "Выполняю push..."
            git pull --rebase
            git push
            
            commit_after=$(git rev-parse HEAD)

            # --- НОВАЯ, ЖЕЛЕЗОБЕТОННАЯ ЛОГИКА INDEXNOW ---
            NEW_FILES=$(git diff --name-only $commit_before $commit_after -- 'src/content/posts/*.md')
            
            if [[ -n "$NEW_FILES" ]]; then
              echo "📢 Подготовка уведомления для IndexNow..."
              API_KEY="d1b055ab1eb146d892169bbb2c96550e"
              HOST="butlerspb-blog.netlify.app"
              
              # Собираем URL в одну строку, разделенную пробелами
              URL_LIST_STRING=""
              for file in $NEW_FILES; do
                slug=$(basename $file .md)
                url="https://butlerspb-blog.netlify.app/blog/${slug}/"
                URL_LIST_STRING="$URL_LIST_STRING $url"
              done
              
              # jq сам "нарежет" эту строку на массив
              JSON_PAYLOAD=$(jq -n \
                              --arg host "$HOST" \
                              --arg key "$API_KEY" \
                              --arg urls "$URL_LIST_STRING" \
                              '{host: $host, key: $key, urlList: ($urls | split(" ") | map(select(length > 0)))}'
                              )

              # --- ДИАГНОСТИКА ---
              echo "--- Диагностика пакета для IndexNow (пачка №$i) ---"
              echo "$JSON_PAYLOAD"
              echo "--- Конец диагностики ---"
              
              echo "--- Отправка в Яндекс ---"
              curl -X POST "https://yandex.com/indexnow" -H "Content-Type: application/json; charset=utf-8" -d "$JSON_PAYLOAD"
              
              echo -e "\n--- Отправка в Bing ---"
              curl -X POST "https://www.bing.com/indexnow" -H "Content-Type: application/json; charset=utf-8" -d "$JSON_PAYLOAD"
            fi
            
            echo -e "\n✅ Пачка $i успешно обработана и отправлена в IndexNow."
          done
