name: 🚀 Content Factory (Diagnostic Mode)

on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'Сколько статей генерировать за 1 итерацию?'
        required: true
        default: '50'
      iterations:
        description: 'Сколько раз запустить конвейер?'
        required: true
        default: '10'

jobs:
  build:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏭 Run Content Factory Conveyor
        id: factory_run
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BATCH_SIZE: ${{ github.event.inputs.batch_size }}
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          
          ALL_NEW_URLS=""

          for i in $(seq 1 ${{ github.event.inputs.iterations }})
          do
            echo "--- КОНВЕЙЕР: Запуск итерации $i из ${{ github.event.inputs.iterations }} ---"
            
            commit_before=$(git rev-parse HEAD)
            
            npm run factory
            
            # --- НАЧАЛО ДИАГНОСТИЧЕСКОГО БЛОКА ---
            echo "--- Диагностика Git ---"
            echo "Проверяю статус файлов..."
            git status

            if [[ -z $(git status --porcelain) ]]; then
              echo "✅ Новых файлов для коммита не найдено. Завершаю итерацию."
              continue # Переходим к следующей итерации, если она есть
            fi
            
            echo "🔥 Обнаружены новые файлы. Добавляю в индекс..."
            git add .

            echo "Проверяю статус после 'git add':"
            git status

            echo "Выполняю коммит..."
            git commit -m "🚀 Авто-публикация: пачка статей №$i"

            echo "Выполняю push..."
            git push
            # --- КОНЕЦ ДИАГНОСТИЧЕСКОГО БЛОКА ---
            
            commit_after=$(git rev-parse HEAD)

            NEW_FILES=$(git diff --name-only $commit_before $commit_after -- 'src/content/posts/*.md')
            
            for file in $NEW_FILES; do
              slug=$(basename $file .md)
              url="https://butlerspb-blog.netlify.app/blog/${slug}/"
              ALL_NEW_URLS="${ALL_NEW_URLS}${url}\n"
            done

            echo "✅ Пачка $i успешно обработана."
          done

          echo "urllist<<EOF" >> $GITHUB_OUTPUT
          echo -e "$ALL_NEW_URLS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 📢 Notify IndexNow
        if: steps.factory_run.outputs.urllist
        run: |
          echo "Отправляю уведомление о новых страницах в IndexNow..."
          API_KEY="d1b055ab1eb146d892169bbb2c96550e"
          HOST="butlerspb-blog.netlify.app"
          
          JSON_PAYLOAD=$(jq -n \
                          --arg host "$HOST" \
                          --arg key "$API_KEY" \
                          --argjson urls "$(echo '${{ steps.factory_run.outputs.urllist }}' | jq -R . | jq -s .)" \
                          '{host: $host, key: $key, urlList: $urls}')

          curl -X POST "https://yandex.com/indexnow" \
               -H "Content-Type: application/json; charset=utf-8" \
               -d "$JSON_PAYLOAD"
          echo -e "\nУведомление отправлено."```
</details>

**Что мы изменили:**
*   Я убрал конструкцию `if/else`, чтобы упростить логику.
*   Я добавил явные команды `git status` до и после `git add .`.
*   Я изменил сообщение в конце итерации.

**Ваши действия:**
1.  Замените код в файле `.github/workflows/factory.yml`.
2.  Запустите воркфлоу еще раз с настройками "1 статья, 1 итерация".
3.  **Пришлите мне лог этого нового запуска.**

Теперь лог будет гораздо более подробным. Мы увидим, видит ли `git` новые файлы, добавляет ли он их в "индекс" для коммита, и что происходит непосредственно перед командой `push`. Это даст нам финальный ответ. Мы на пороге разгадки.
