name: 🚀 Content Factory (Unified Arsenal)

on:
  workflow_dispatch:
    inputs:
      batch_size_per_thread:
        description: 'Сколько статей генерировать КАЖДЫМ потоком?'
        required: true
        default: '10'
      threads:
        description: 'Сколько потоков запустить ОДНОВРЕМЕННО?'
        required: true
        default: '5'

jobs:
  generate_and_publish:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        thread: ${{ fromJson(format('[{0}]', range(1, github.event.inputs.threads + 1))) }}

    steps:
      - name: ⬇️ Checkout repo (Thread ${{ matrix.thread }})
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: ⚙️ Setup Node.js (Thread ${{ matrix.thread }})
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install dependencies (Thread ${{ matrix.thread }})
        run: npm install

      - name: 🔑 Set API Key for Thread ${{ matrix.thread }}
        id: set_key
        run: |
          API_KEYS="${{ secrets.GEMINI_API_KEYS_POOL }}"
          KEY_INDEX=$((${{ matrix.thread }} - 1))
          # Используем sed для извлечения нужной строки. awk - более надежный вариант
          CURRENT_KEY=$(echo "$API_KEYS" | awk "NR==${{ matrix.thread }}")
          if [[ -z "$CURRENT_KEY" ]]; then
            echo "::error::Не удалось извлечь API-ключ для потока #${{ matrix.thread }}. Проверьте секрет GEMINI_API_KEYS_POOL."
            exit 1
          fi
          echo "key=$CURRENT_KEY" >> $GITHUB_OUTPUT

      - name: 🏭 Run Factory & 📢 Publish & Notify (Thread ${{ matrix.thread }})
        env:
          GEMINI_API_KEY_CURRENT: ${{ steps.set_key.outputs.key }}
          BATCH_SIZE: ${{ github.event.inputs.batch_size_per_thread }}
          TOTAL_THREADS: ${{ github.event.inputs.threads }}
          THREAD_ID: ${{ matrix.thread }}
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          
          echo "--- ЭСКАДРОН #${{ matrix.thread }}: Начинаю генерацию ---"
          
          git pull --rebase

          commit_before=$(git rev-parse HEAD)
          
          npm run factory
          
          if [[ -z $(git status --porcelain) ]]; then
            echo "✅ ЭСКАДРОН #${{ matrix.thread }}: Новых статей для этого потока не найдено. Миссия завершена."
            exit 0
          fi

          echo "🔥 ЭСКАДРОН #${{ matrix.thread }}: Обнаружены новые файлы. Публикую пачку..."
          git add src/content/posts/*.md
          git commit -m "🚀 Авто-публикация: пачка от Эскадрона №${{ matrix.thread }}"
          
          git pull --rebase
          git push
          
          commit_after=$(git rev-parse HEAD)

          NEW_FILES=$(git diff --name-only $commit_before $commit_after -- 'src/content/posts/*.md')
          
          URL_LIST=""
          for file in $NEW_FILES; do
            slug=$(basename $file .md)
            url="https://butlerspb-blog.netlify.app/blog/${slug}/"
            URL_LIST="${URL_LIST}${url}\n"
          done

          if [[ -n "$URL_LIST" ]]; then
            echo "📢 ЭСКАДРОН #${{ matrix.thread }}: Отправляю уведомление в IndexNow..."
            API_KEY="d1b055ab1eb146d892169bbb2c96550e"
            HOST="butlerspb-blog.netlify.app"
            
            JSON_PAYLOAD=$(jq -n \
                            --arg host "$HOST" \
                            --arg key "$API_KEY" \
                            --arg urls_string "$URL_LIST" \
                            '{host: $host, key: $key, urlList: ($urls_string | split("\n") | map(select(length > 0)))}'
                            )
            
            curl -X POST "https://yandex.com/indexnow" -H "Content-Type: application/json; charset=utf-8" -d "$JSON_PAYLOAD"
            curl -X POST "https://www.bing.com/indexnow" -H "Content-Type: application/json; charset=utf-8" -d "$JSON_PAYLOAD"
          fi
          
          echo -e "\n✅ ЭСКАДРОН #${{ matrix.thread }}: Миссия успешно завершена."
