name: 🚀 Content Factory (Conveyor Mode)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Получаем код из репозитория
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        # ВАЖНО: Даем права на push обратно в репозиторий
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      # 2. Устанавливаем Node.js
      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Устанавливаем зависимости (этот шаг выполняется один раз)
      - name: 📦 Install dependencies
        run: npm install

      # 4. НАЧАЛО КОНВЕЙЕРА
      - name: 🏭 Run Content Factory Conveyor
        run: |
          # Настраиваем Git ОДИН РАЗ перед циклом
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          
          # Запускаем конвейер в цикле. 5 раз по 50 статей = до 250 статей.
          # Вы можете изменить {1..5} на {1..10}, если тем будет больше.
          for i in {1..5}
          do
            echo "--- КОНВЕЙЕР: Запуск итерации $i ---"
            
            # Запускаем завод, который сгенерирует СЛЕДУЮЩИЕ 50 статей
            npm run factory
            
            # Проверяем, были ли созданы новые файлы в этой итерации
            if [[ -z $(git status --porcelain) ]]; then
              echo "✅ Новых статей в этой итерации нет. Работа полностью завершена."
              break # Выходим из цикла, если все темы обработаны
            fi

            # Если файлы есть, немедленно их публикуем
            echo "🔥 Обнаружены новые статьи. Отправляю пачку $i..."
            git add .
            git commit -m "🚀 Авто-публикация: пачка статей №$i"
            git push
            echo "✅ Пачка $i успешно отправлена на публикацию."
          done
