name: 🚀 Content Factory (Central Dispatch)

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
      
      - name: 📝 Generate job list
        id: set-matrix
        run: |
          ALL_TOPICS=$(cat topics.txt | jq -R . | jq -s .)
          EXISTING_FILES=$(ls src/content/posts | jq -R . | jq -s .)
          
          NEW_TOPICS=$(jq -n --argjson all_topics "$ALL_TOPICS" --argjson existing_files "$EXISTING_FILES" \
            '($existing_files | map( sub(".md$"; "") )) as $slugs |
             $all_topics | map(select(. != "" and . != null)) |
             map(select(IN($slugs; (. | ascii_downcase | gsub(" "; "-") | gsub("[^a-z0-9-]"; ""))) | not))')

          echo "Найдено $(echo $NEW_TOPICS | jq 'length') новых тем для генерации."
          echo "matrix=$(echo $NEW_TOPICS | jq -c .)" >> $GITHUB_OUTPUT

  generate:
    needs: prepare
    if: needs.prepare.outputs.matrix != '[]'
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        topic: ${{ fromJson(needs.prepare.outputs.matrix) }}
        key_index: ${{ fromJson(format('[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]')) }}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
      
      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔑 Set API Key
        id: set_key
        run: |
          API_KEYS="${{ secrets.GEMINI_API_KEYS_POOL }}"
          KEY_COUNT=$(echo "$API_KEYS" | wc -l)
          CURRENT_KEY_INDEX=$(( (${{ matrix.key_index }} % $KEY_COUNT) + 1 ))
          CURRENT_KEY=$(echo "$API_KEYS" | sed -n "${CURRENT_KEY_INDEX}p" | tr -d '\r')
          echo "key=$CURRENT_KEY" >> $GITHUB_OUTPUT

      - name: 🏭 Run Factory for "${{ matrix.topic }}"
        env:
          GEMINI_API_KEY: ${{ steps.set_key.outputs.key }}
          TOPIC: ${{ matrix.topic }}
        run: npm run factory
        
  publish:
    needs: [prepare, generate]
    if: always()
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🚀 Commit and Push All New Posts
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'

          if [[ -z $(git status --porcelain "src/content/posts/") ]]; then
            echo "✅ Новых статей для публикации не найдено."
            exit 0
          fi
          
          git add src/content/posts/*.md
          git commit -m "🚀 Авто-публикация: новая пачка статей"
          git pull --rebase
          git push

      - name: 📢 Notify IndexNow
        if: success()
        run: |
          NEW_FILES=$(git diff --name-only HEAD~1 HEAD -- 'src/content/posts/*.md')
          if [[ -z "$NEW_FILES" ]]; then exit 0; fi
          
          URL_JSON_ARRAY=$(for file in $NEW_FILES; do slug=$(basename "$file" .md); echo "https://butlerspb-blog.netlify.app/blog/${slug}/"; done | jq -R . | jq -s .)
          
          API_KEY="d1b055ab1eb146d892169bbb2c96550e"
          HOST="butlerspb-blog.netlify.app"

          JSON_PAYLOAD=$(jq -n \
                          --arg host "$HOST" \
                          --arg key "$API_KEY" \
                          --argjson urls "$URL_JSON_ARRAY" \
                          '{host: $host, key: $key, urlList: $urls}')
          
          echo "--- Отправка в Яндекс и Bing ---"
          curl -X POST "https://yandex.com/indexnow" -H "Content-Type: application/json; charset=utf-8" -d "$JSON_PAYLOAD"
          curl -X POST "https://www.bing.com/indexnow" -H "Content-Type: application/json; charset=utf-8" -d "$JSON_PAYLOAD"
