name: 🚀 Content Factory

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        
      # ЭТОТ БЛОК ТЕПЕРЬ СОДЕРЖИТ "ОЧИСТКУ КЭША"
      - name: ⚙️ Setup Node.js with Cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Добавляем ключ кеша, чтобы сбросить старые данные
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # ЭТО ГЛАВНОЕ ИСПРАВЛЕНИЕ: ПРАВИЛЬНАЯ КОМАНДА УСТАНОВКИ
      - name: 📦 Install dependencies
        run: npm install

      - name: 🏭 Run Content Factory
        run: npm run factory
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: 🚀 Commit and Push new posts
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          
          # Проверяем, есть ли изменения
          if [[ -z $(git status --porcelain) ]]; then
            echo "✅ Нет новых статей или изменений. Работа завершена."
            exit 0
          fi
          
          echo "🔥 Обнаружены новые файлы. Начинаю отправку..."
          git add .
          git commit -m "🚀 Автоматически добавлены новые статьи и файлы"
          git push
