name: 🚀 Content Factory (Bulletproof Batch Push v3)

on:
  workflow_dispatch:
    inputs:
      model_choice:
        description: 'Какую модель использовать для генерации?'
        required: true
        default: 'gemini'
        type: choice
        options:
        - gemini
        - deepseek
      batch_size_per_thread:
        description: 'Сколько статей генерировать КАЖДЫМ потоком?'
        required: true
        default: '10'
      threads:
        description: 'Сколько потоков запустить ОДНОВРЕМЕННО (1-20)?'
        required: true
        default: '5'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: Create thread matrix
        id: set_matrix
        run: |
          MAX_THREADS=20
          REQUESTED_THREADS=${{ github.event.inputs.threads || 5 }}
          
          if (( REQUESTED_THREADS > MAX_THREADS )); then
            echo "::warning::Запрошено больше потоков (${REQUESTED_THREADS}), чем доступно ключей (${MAX_THREADS}). Будет использовано ${MAX_THREADS}."
            REQUESTED_THREADS=$MAX_THREADS
          fi

          MATRIX=$(jq -cn --argjson n "$REQUESTED_THREADS" '[range(1; $n + 1)]')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  generate:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        thread: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔑 Set API Key
        id: set_key
        run: |
          MODEL_CHOICE="${{ github.event.inputs.model_choice || 'gemini' }}"
          if [ "$MODEL_CHOICE" == "deepseek" ]; then
            API_KEYS="${{ secrets.OPENROUTER_API_KEYS_POOL }}"
          else
            API_KEYS="${{ secrets.GEMINI_API_KEYS_POOL }}"
          fi
          CURRENT_KEY=$(echo "$API_KEYS" | sed -n '${{ matrix.thread }}p' | tr -d '\r')
          if [[ -z "$CURRENT_KEY" ]]; then
            echo "::error::Не удалось извлечь API-ключ для потока #${{ matrix.thread }}."
            exit 1
          fi
          echo "key=$CURRENT_KEY" >> $GITHUB_OUTPUT

      - name: 🏭 Run Factory (Thread ${{ matrix.thread }})
        env:
          MODEL_CHOICE: ${{ github.event.inputs.model_choice || 'gemini' }}
          API_KEY_CURRENT: ${{ steps.set_key.outputs.key }}
          BATCH_SIZE: ${{ github.event.inputs.batch_size_per_thread || 10 }}
          TOTAL_THREADS: ${{ github.event.inputs.threads || 5 }}
          THREAD_ID: ${{ matrix.thread }}
        run: npm run factory

      - name: 📤 Upload generated articles
        uses: actions/upload-artifact@v4
        with:
          name: generated-posts-thread-${{ matrix.thread }}
          path: src/content/posts/*.md
          if-no-files-found: ignore

  publish_and_notify:
    if: ${{ always() }} 
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📥 Download all generated articles
        uses: actions/download-artifact@v4
        with:
          path: src/content/posts
          merge-multiple: true

      - name: 🚀 Commit, Push & Notify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --global pull.rebase true

          if [[ -z $(git status --porcelain src/content/posts/) ]]; then
            echo "✅ Новых статей для публикации не найдено."
            exit 0
          fi

          echo "🔥 Обнаружены новые файлы. Начинаю процедуру публикации..."
          git pull
          
          # Получаем список именно новых, неотслеживаемых файлов
          NEW_FILES=$(git status --porcelain src/content/posts/ | grep '^??' | awk '{print $2}')
          
          git add src/content/posts/*.md
          git commit -m "🚀 Авто-публикация: пакетная сборка"
          
          # Используем правильный метод аутентификации для push
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:main

          if [[ -n "$NEW_FILES" ]]; then
            echo "📢 Подготовка уведомления для IndexNow..."
            API_KEY="d1b055ab1eb146d892169bbb2c96550e"
            HOST="butlerspb-blog.netlify.app"
            URL_JSON_ARRAY=$(for file in $NEW_FILES; do slug=$(basename "$file" .md); echo "https://butlerspb-blog.netlify.app/blog/${slug}/"; done | jq -R . | jq -s .)
            JSON_PAYLOAD=$(jq -n --arg host "$HOST" --arg key "$API_KEY" --argjson urls "$URL_JSON_ARRAY" '{host: $host, key: $key, urlList: $urls}')
            
            echo "--- Диагностика пакета для IndexNow ---"
            echo "$JSON_PAYLOAD"
            echo "--- Конец диагностики ---"
            
            curl -X POST "https://yandex.com/indexnow" -H "Content-Type: application/json; charset=utf-8" -d "$JSON_PAYLOAD"
            curl -X POST "https://www.bing.com/indexnow" -H "Content-Type: application/json; charset=utf-8" -d "$JSON_PAYLOAD"
          fi
          
          echo -e "\n✅ Миссия успешно завершена."
