name: 🚀 Content Factory (Armored Conveyor)

on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'Сколько статей генерировать за 1 итерацию?'
        required: true
        default: '50'
      iterations:
        description: 'Сколько раз запустить конвейер?'
        required: true
        default: '10'

jobs:
  build:
    # ВОТ КЛЮЧЕВОЕ ДОБАВЛЕНИЕ - ВЫДАЕМ ПРАВА
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏭 Run Content Factory Conveyor
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BATCH_SIZE: ${{ github.event.inputs.batch_size }}
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          
          for i in $(seq 1 ${{ github.event.inputs.iterations }})
          do
            echo "--- КОНВЕЙЕР: Запуск итерации $i из ${{ github.event.inputs.iterations }} ---"
            npm run factory
            
            # Проверяем, есть ли изменения (статьи или package-lock.json)
            if [[ -z $(git status --porcelain) ]]; then
              echo "✅ Новых статей в этой итерации нет. Работа полностью завершена."
              break
            fi

            echo "🔥 Обнаружены новые файлы. Отправляю пачку $i..."
            git add .
            git commit -m "🚀 Авто-публикация: пачка статей №$i"
            git push
            echo "✅ Пачка $i успешно отправлена на публикацию."
          done
